//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BASE_LEGAL
    {
        public T_BASE_LEGAL()
        {
            this.T_PLAN_BASE_LEGAL = new HashSet<T_PLAN_BASE_LEGAL>();
        }
    
        public int id_base_legal { get; set; }
        public string nombre_normativa { get; set; }
        public string descripcion { get; set; }
        public string autorizacion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual ICollection<T_PLAN_BASE_LEGAL> T_PLAN_BASE_LEGAL { get; set; }
    }
}
