//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BIEN
    {
        public T_BIEN()
        {
            this.T_MUEBLE = new HashSet<T_MUEBLE>();
            this.T_INMUEBLE = new HashSet<T_INMUEBLE>();
        }
    
        public int codBien { get; set; }
        public string dscBien { get; set; }
        public Nullable<System.DateTime> fecAdquisicion { get; set; }
    
        public virtual ICollection<T_MUEBLE> T_MUEBLE { get; set; }
        public virtual ICollection<T_INMUEBLE> T_INMUEBLE { get; set; }
    }
}
