//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BITACORA_INCIDENCIA
    {
        public T_BITACORA_INCIDENCIA()
        {
            this.T_SEGUIMIENTO = new HashSet<T_SEGUIMIENTO>();
        }
    
        public int id_bitacora { get; set; }
        public string tipo_incidencia { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_plan_salud { get; set; }
        public Nullable<int> idempleado { get; set; }
        public string estado { get; set; }
    
        public virtual T_EMPLEADO T_EMPLEADO { get; set; }
        public virtual T_PLAN_DE_SALUD T_PLAN_DE_SALUD { get; set; }
        public virtual ICollection<T_SEGUIMIENTO> T_SEGUIMIENTO { get; set; }
    }
}
