//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONFIGURACION
    {
        public int id_configuracion { get; set; }
        public string modulo { get; set; }
        public string area { get; set; }
        public string indicador { get; set; }
        public string valor_minimo { get; set; }
        public string valor_maximo { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> id_investigacion_comercial { get; set; }
    
        public virtual T_INVESTIGACION_COMERCIAL T_INVESTIGACION_COMERCIAL { get; set; }
    }
}
