//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EMPLEADO
    {
        public T_EMPLEADO()
        {
            this.T_BITACORA_INCIDENCIA = new HashSet<T_BITACORA_INCIDENCIA>();
            this.T_SOLICITUD_MANTENIMIENTO = new HashSet<T_SOLICITUD_MANTENIMIENTO>();
            this.T_TECNICO_MANTENIMIENTO = new HashSet<T_TECNICO_MANTENIMIENTO>();
            this.T_PROGRAMACION_MEDICA = new HashSet<T_PROGRAMACION_MEDICA>();
        }
    
        public int idEmpleado { get; set; }
        public Nullable<int> nroDni { get; set; }
        public string nomEmpleado { get; set; }
        public Nullable<System.DateTime> fecIngreso { get; set; }
        public string stdEmplead { get; set; }
        public string dscCargo { get; set; }
        public string dscProfesion { get; set; }
        public string dscArea { get; set; }
        public string dscCorreo { get; set; }
        public Nullable<int> idEspecialidad { get; set; }
        public Nullable<int> codPersona { get; set; }
    
        public virtual ICollection<T_BITACORA_INCIDENCIA> T_BITACORA_INCIDENCIA { get; set; }
        public virtual T_PERSONA T_PERSONA { get; set; }
        public virtual ICollection<T_SOLICITUD_MANTENIMIENTO> T_SOLICITUD_MANTENIMIENTO { get; set; }
        public virtual ICollection<T_TECNICO_MANTENIMIENTO> T_TECNICO_MANTENIMIENTO { get; set; }
        public virtual T_ESPECIALIDAD_MEDICA T_ESPECIALIDAD_MEDICA { get; set; }
        public virtual ICollection<T_PROGRAMACION_MEDICA> T_PROGRAMACION_MEDICA { get; set; }
    }
}
