//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ESTRATEGIA_COMERCIAL
    {
        public T_ESTRATEGIA_COMERCIAL()
        {
            this.T_PLAN_ESTRATEGIA_COMERCIAL = new HashSet<T_PLAN_ESTRATEGIA_COMERCIAL>();
            this.T_ESTRATEGIA_COMERCIAL_DETALLE = new HashSet<T_ESTRATEGIA_COMERCIAL_DETALLE>();
        }
    
        public int id_estrategia_comercial { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string objetivo { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public decimal presupuesto { get; set; }
        public int id_plan_salud { get; set; }
    
        public virtual ICollection<T_PLAN_ESTRATEGIA_COMERCIAL> T_PLAN_ESTRATEGIA_COMERCIAL { get; set; }
        public virtual T_PLAN_DE_SALUD T_PLAN_DE_SALUD { get; set; }
        public virtual ICollection<T_ESTRATEGIA_COMERCIAL_DETALLE> T_ESTRATEGIA_COMERCIAL_DETALLE { get; set; }
    }
}
