//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ESTRATEGIA_COMERCIAL_DETALLE
    {
        public int id_estrategia_detalle { get; set; }
        public string medio_campana { get; set; }
        public string canal { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public decimal monto { get; set; }
        public string objetivo { get; set; }
        public string estado { get; set; }
        public string usuario { get; set; }
        public byte[] comprobante { get; set; }
        public int id_estrategia_comercial { get; set; }
    
        public virtual T_ESTRATEGIA_COMERCIAL T_ESTRATEGIA_COMERCIAL { get; set; }
    }
}
