//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INMUEBLE
    {
        public T_INMUEBLE()
        {
            this.T_EQUIPO_MEDICO = new HashSet<T_EQUIPO_MEDICO>();
            this.T_PROGRAMACION_MEDICA = new HashSet<T_PROGRAMACION_MEDICA>();
        }
    
        public int codInmueble { get; set; }
        public string dscTipoEstado { get; set; }
        public Nullable<int> codBien { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual T_BIEN T_BIEN { get; set; }
        public virtual ICollection<T_EQUIPO_MEDICO> T_EQUIPO_MEDICO { get; set; }
        public virtual ICollection<T_PROGRAMACION_MEDICA> T_PROGRAMACION_MEDICA { get; set; }
    }
}
