//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PACIENTE
    {
        public T_PACIENTE()
        {
            this.T_COMPROBANTE = new HashSet<T_COMPROBANTE>();
            this.T_RESERVA_SERVICIO_SALUD = new HashSet<T_RESERVA_SERVICIO_SALUD>();
            this.T_PLAN_PACIENTE = new HashSet<T_PLAN_PACIENTE>();
        }
    
        public int id_paciente { get; set; }
        public string nom_paciente { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string segmentacion { get; set; }
        public string estado { get; set; }
        public Nullable<int> codPersona { get; set; }
    
        public virtual ICollection<T_COMPROBANTE> T_COMPROBANTE { get; set; }
        public virtual T_PERSONA T_PERSONA { get; set; }
        public virtual ICollection<T_RESERVA_SERVICIO_SALUD> T_RESERVA_SERVICIO_SALUD { get; set; }
        public virtual ICollection<T_PLAN_PACIENTE> T_PLAN_PACIENTE { get; set; }
    }
}
