//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PLAN_DE_SALUD
    {
        public T_PLAN_DE_SALUD()
        {
            this.T_BITACORA_INCIDENCIA = new HashSet<T_BITACORA_INCIDENCIA>();
            this.T_PLAN_BASE_FINANCIERA = new HashSet<T_PLAN_BASE_FINANCIERA>();
            this.T_PLAN_BASE_LEGAL = new HashSet<T_PLAN_BASE_LEGAL>();
            this.T_PLAN_ESTRATEGIA_COMERCIAL = new HashSet<T_PLAN_ESTRATEGIA_COMERCIAL>();
            this.T_PLAN_PACIENTE = new HashSet<T_PLAN_PACIENTE>();
            this.T_PERSONA_PLANSALUD = new HashSet<T_PERSONA_PLANSALUD>();
            this.T_PLAN_SERVICIO = new HashSet<T_PLAN_SERVICIO>();
            this.T_ESTRATEGIA_COMERCIAL = new HashSet<T_ESTRATEGIA_COMERCIAL>();
        }
    
        public int id_plan_salud { get; set; }
        public string nombre_plan { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string objetivo { get; set; }
        public Nullable<int> id_investigacion_comercial { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<T_BITACORA_INCIDENCIA> T_BITACORA_INCIDENCIA { get; set; }
        public virtual T_INVESTIGACION_COMERCIAL T_INVESTIGACION_COMERCIAL { get; set; }
        public virtual ICollection<T_PLAN_BASE_FINANCIERA> T_PLAN_BASE_FINANCIERA { get; set; }
        public virtual ICollection<T_PLAN_BASE_LEGAL> T_PLAN_BASE_LEGAL { get; set; }
        public virtual ICollection<T_PLAN_ESTRATEGIA_COMERCIAL> T_PLAN_ESTRATEGIA_COMERCIAL { get; set; }
        public virtual ICollection<T_PLAN_PACIENTE> T_PLAN_PACIENTE { get; set; }
        public virtual ICollection<T_PERSONA_PLANSALUD> T_PERSONA_PLANSALUD { get; set; }
        public virtual ICollection<T_PLAN_SERVICIO> T_PLAN_SERVICIO { get; set; }
        public virtual ICollection<T_ESTRATEGIA_COMERCIAL> T_ESTRATEGIA_COMERCIAL { get; set; }
    }
}
