//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PLAN_PACIENTE
    {
        public int id_plan_paciente { get; set; }
        public Nullable<int> id_paciente { get; set; }
        public Nullable<int> id_plan_salud { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string estado { get; set; }
    
        public virtual T_PACIENTE T_PACIENTE { get; set; }
        public virtual T_PLAN_DE_SALUD T_PLAN_DE_SALUD { get; set; }
    }
}
