//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROGRAMACION_MEDICA
    {
        public int id_programacion { get; set; }
        public Nullable<int> prestaciones { get; set; }
        public Nullable<int> dis_prestaciones { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_fin { get; set; }
        public string anotaciones { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
        public int id_empleado { get; set; }
        public Nullable<int> codInmueble { get; set; }
        public int codPersona { get; set; }
        public int id_servicio { get; set; }
        public int idEspecialidad { get; set; }
    
        public virtual T_EMPLEADO T_EMPLEADO { get; set; }
        public virtual T_INMUEBLE T_INMUEBLE { get; set; }
        public virtual T_PERSONA T_PERSONA { get; set; }
        public virtual T_ESPECIALIDAD_SERVICIO T_ESPECIALIDAD_SERVICIO { get; set; }
    }
}
