//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROYECTO_PLANSALUD
    {
        public int id_proyecto { get; set; }
        public string nombre_proyecto { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public short estado { get; set; }
        public Nullable<int> id_investigacion_comercial { get; set; }
    
        public virtual T_INVESTIGACION_COMERCIAL T_INVESTIGACION_COMERCIAL { get; set; }
    }
}
