//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RESERVA_SERVICIO_SALUD
    {
        public int id_reserva { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }
        public string tipo_atencion { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_paciente { get; set; }
        public Nullable<int> id_servicio { get; set; }
    
        public virtual T_PACIENTE T_PACIENTE { get; set; }
        public virtual T_SERVICIO_SALUD T_SERVICIO_SALUD { get; set; }
    }
}
